export {SignupRoutes} from './signupRoutes';
export {SigninRoutes} from './signinRoutes';
export {GamesRoutes} from './gamesRoutes';
export {TeamRoutes} from './TeamRoutes';
export {GameBetRoutes} from './gameBetRoutes';
export {ChampionBetRoutes} from './championBetRoutes';
export {InvitationRoutes} from './invitationRoutes';
export {VerifyRoutes} from './verifyRoutes';
export {ResetPasswordRoutes} from './resetPasswordRoutes';
