"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var enzyme_1 = require("enzyme");
var enzyme_adapter_react_16_1 = require("enzyme-adapter-react-16");
var jest_fetch_mock_1 = require("jest-fetch-mock");
var faker_1 = require("faker");
var LocalStorageMock_1 = require("./test/mocks/LocalStorageMock");
enzyme_1.configure({ adapter: new enzyme_adapter_react_16_1.default() });
global.fetch = jest_fetch_mock_1.default;
jest_fetch_mock_1.default.enableMocks();
faker_1.default.seed(123456);
global['localStorage'] = new LocalStorageMock_1.LocalStorageMock();
