"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.Root = exports.Label = exports.Inner = exports.CheckboxInput = void 0;
var styled_components_1 = require("styled-components");
var styles_config_1 = require("../../styles/styles-config");
exports.CheckboxInput = styled_components_1.default.input(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  position: absolute;\n  z-index: -1;\n  opacity: 0;\n"], ["\n  position: absolute;\n  z-index: -1;\n  opacity: 0;\n"])));
exports.CheckboxInput.defaultProps = Object.freeze({
    type: "checkbox",
});
exports.Inner = styled_components_1.default.label(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  &:before {\n    position: absolute;\n    content: \"\";\n    top: 0;\n    display: block;\n    width: 35px;\n    height: 16px;\n    background: ", ";\n    border: 1px solid ", ";\n    border-radius: 100px;\n    will-change: background-color, border-color;\n    transition-property: background-color, border-color;\n    transition-duration: 350ms;\n  }\n\n  &:after {\n    content: \"\";\n    position: absolute;\n    background: ", ";\n    border-radius: 100px;\n    top: 3px;\n    left: 4px;\n    width: 12px;\n    height: 12px;\n    will-change: background-color, transform;\n    transition-property: background-color, transform;\n    transition-duration: 350ms;\n  }\n\n  ", ";\n"], ["\n  &:before {\n    position: absolute;\n    content: \"\";\n    top: 0;\n    display: block;\n    width: 35px;\n    height: 16px;\n    background: ", ";\n    border: 1px solid ", ";\n    border-radius: 100px;\n    will-change: background-color, border-color;\n    transition-property: background-color, border-color;\n    transition-duration: 350ms;\n  }\n\n  &:after {\n    content: \"\";\n    position: absolute;\n    background: ", ";\n    border-radius: 100px;\n    top: 3px;\n    left: 4px;\n    width: 12px;\n    height: 12px;\n    will-change: background-color, transform;\n    transition-property: background-color, transform;\n    transition-duration: 350ms;\n  }\n\n  ",
    ";\n"])), styles_config_1.stylesConfig.color.white, styles_config_1.stylesConfig.color.secondary, styles_config_1.stylesConfig.color.secondary, function (_a) {
    var disabled = _a.disabled;
    return disabled && styled_components_1.css(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n      cursor: not-allowed;\n      opacity: ", ";\n    "], ["\n      cursor: not-allowed;\n      opacity: ", ";\n    "])), styles_config_1.stylesConfig.opacity.disabled);
});
exports.Label = styled_components_1.default.span(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n  font-size: ", ";\n  font-family: ", ";\n  color: ", ";\n  padding-left: 45px;\n  cursor: pointer;\n"], ["\n  font-size: ", ";\n  font-family: ", ";\n  color: ", ";\n  padding-left: 45px;\n  cursor: pointer;\n"])), styles_config_1.stylesConfig.fontSize.normal, styles_config_1.stylesConfig.fontFamily.primary, styles_config_1.stylesConfig.color.textColor);
exports.Root = styled_components_1.default.label(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n  position: relative;\n  display: flex;\n\n  ", ":checked ~ ", ":before {\n    background-color: ", ";\n    border-color: ", ";\n  }\n\n  ", ":checked ~ ", ":after {\n    background-color: ", ";\n    transform: translateX(100%);\n    left: 10px;\n  }\n"], ["\n  position: relative;\n  display: flex;\n\n  ", ":checked ~ ", ":before {\n    background-color: ", ";\n    border-color: ", ";\n  }\n\n  ", ":checked ~ ", ":after {\n    background-color: ", ";\n    transform: translateX(100%);\n    left: 10px;\n  }\n"])), exports.CheckboxInput, exports.Inner, styles_config_1.stylesConfig.color.primary, styles_config_1.stylesConfig.color.primary, exports.CheckboxInput, exports.Inner, styles_config_1.stylesConfig.color.white);
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5;
