"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.Label = exports.Wrapper = exports.Inner = exports.CheckboxInput = void 0;
var styled_components_1 = require("styled-components");
var styles_1 = require("../../styles");
exports.CheckboxInput = styled_components_1.default.input(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  position: absolute;\n  z-index: -1;\n  opacity: 0;\n"], ["\n  position: absolute;\n  z-index: -1;\n  opacity: 0;\n"])));
exports.CheckboxInput.defaultProps = {
    type: 'checkbox',
};
exports.Inner = styled_components_1.default.label(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  position: relative;\n  padding-left: 30px;\n  cursor: pointer;\n  &:before {\n    content: '';\n    position: absolute;\n    display: block;\n    left: 0;\n    width: 16px;\n    height: 16px;\n    background-color: ", ";\n    border: 1px solid ", ";\n    user-select: none;\n    border-radius: 2px;\n    pointer-events: all;\n    transition-property: background-image, background-color, border-color,\n      box-shadow;\n    transition-duration: 0.25s;\n    transition-timing-function: cubic-bezier(0.27, 0.01, 0.38, 1.06);\n  }\n\n  ", ":checked ~ &:before {\n    background-image: none;\n    background-color: ", ";\n    color: ", ";\n    border-color: transparent;\n    box-shadow: none;\n  }\n\n  &:after {\n    content: '';\n    position: absolute;\n    display: block;\n    left: 6px;\n    width: 5px;\n    height: 11px;\n    opacity: 0;\n    transform: rotate(45deg) scale(0);\n    border-right: 2px solid ", ";\n    border-bottom: 2px solid ", ";\n    transition: transform 0.25s cubic-bezier(0.27, 0.01, 0.38, 1.06);\n    background-size: 50% 50%;\n    background-repeat: no-repeat;\n    background-position: 50%;\n  }\n\n  ", ":checked ~ &:after {\n    opacity: 1;\n    -webkit-transform: rotate(45deg) scale(1);\n    transform: rotate(45deg) scale(1);\n    background-image: none;\n  }\n"], ["\n  position: relative;\n  padding-left: 30px;\n  cursor: pointer;\n  &:before {\n    content: '';\n    position: absolute;\n    display: block;\n    left: 0;\n    width: 16px;\n    height: 16px;\n    background-color: ", ";\n    border: 1px solid ", ";\n    user-select: none;\n    border-radius: 2px;\n    pointer-events: all;\n    transition-property: background-image, background-color, border-color,\n      box-shadow;\n    transition-duration: 0.25s;\n    transition-timing-function: cubic-bezier(0.27, 0.01, 0.38, 1.06);\n  }\n\n  ", ":checked ~ &:before {\n    background-image: none;\n    background-color: ", ";\n    color: ", ";\n    border-color: transparent;\n    box-shadow: none;\n  }\n\n  &:after {\n    content: '';\n    position: absolute;\n    display: block;\n    left: 6px;\n    width: 5px;\n    height: 11px;\n    opacity: 0;\n    transform: rotate(45deg) scale(0);\n    border-right: 2px solid ", ";\n    border-bottom: 2px solid ", ";\n    transition: transform 0.25s cubic-bezier(0.27, 0.01, 0.38, 1.06);\n    background-size: 50% 50%;\n    background-repeat: no-repeat;\n    background-position: 50%;\n  }\n\n  ", ":checked ~ &:after {\n    opacity: 1;\n    -webkit-transform: rotate(45deg) scale(1);\n    transform: rotate(45deg) scale(1);\n    background-image: none;\n  }\n"])), styles_1.config.color.white, styles_1.config.color.secondary, exports.CheckboxInput, styles_1.config.color.primary, styles_1.config.color.white, styles_1.config.color.white, styles_1.config.color.white, exports.CheckboxInput);
exports.Wrapper = styled_components_1.default.label(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n  position: relative;\n  display: flex;\n  height: 18px;\n  transition: opacity 0.25s ease-in-out;\n  cursor: pointer;\n\n  ", "\n\n  & + & {\n    margin-top: ", ";\n  }\n"], ["\n  position: relative;\n  display: flex;\n  height: 18px;\n  transition: opacity 0.25s ease-in-out;\n  cursor: pointer;\n\n  ",
    "\n\n  & + & {\n    margin-top: ", ";\n  }\n"])), function (_a) {
    var disabled = _a.disabled;
    return disabled && styled_components_1.css(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n      opacity: ", ";\n      cursor: not-allowed;\n      ", " {\n        cursor: not-allowed;\n      }\n    "], ["\n      opacity: ", ";\n      cursor: not-allowed;\n      ", " {\n        cursor: not-allowed;\n      }\n    "])), styles_1.config.opacity.disabled, exports.Inner);
}, styles_1.config.spacing.small);
exports.Label = styled_components_1.default.span(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n  font-family: ", ";\n  color: ", ";\n  font-size: ", ";\n  ", "\n"], ["\n  font-family: ", ";\n  color: ", ";\n  font-size: ", ";\n  ", "\n"])), styles_1.config.fontFamily.primary, styles_1.config.color.textColor, styles_1.config.fontSize.normal, styles_1.truncate);
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5;
