name: develop-workflow
on:
  push:
    branches:
      - develop
jobs:
  Run-CI:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Install required dependencies
      - run: yarn
      - name: Grant access for script files
      - run: chmod -R +x scripts
      - name: Build packages
      - run: lerna run build
      - name: Run linters
      - run: lerna run lint
      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build docker image
        run: |
          imageId=$(($(date +%s%N)/1000000))
          docker build . -f root.Dockerfile -t "bet/bet-common:$imageId" --no-cache
      - name: docker push
        run: docker push "bet/bet-common:$imageId"
      - run: echo "🍏 This job's status is ${{ job.status }}."
